apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: app-k8s
          image: gabmarte/spring-boot-ci-cd-learning:1.0.0
          ports:
            - containerPort: 8080
#          env:
#            - name: MONGO_URL
#              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always